# Generated by Django 5.2.7 on 2025-10-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('waist_cm', models.FloatField(blank=True, null=True)),
                ('steps_last_24h', models.IntegerField()),
                ('activity_minutes', models.IntegerField()),
                ('sleep_hours_last_24h', models.FloatField()),
                ('water_intake_liters', models.FloatField()),
                ('calories_intake_last_24h', models.IntegerField(blank=True, null=True)),
                ('diet_quality_score', models.IntegerField()),
                ('smoking_status', models.CharField(max_length=20)),
                ('alcohol_units_week', models.IntegerField(blank=True, null=True)),
                ('medications', models.TextField(blank=True)),
                ('known_conditions', models.TextField(blank=True)),
                ('menstrual_cycle_phase', models.CharField(blank=True, max_length=20, null=True)),
                ('mood_score', models.IntegerField()),
                ('stress_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
